# listen:
#   address: ":9130"
#   metricspath: "/metrics"
prometheus_api_query_url: "http://localhost:9090/api/v1/query"
namespace: "time_period_gateway"
metrics:
  - name: "unifi_wan_receive_bytes_total"
    query_template: "sum(increase(unifipoller_device_wan_receive_bytes_total[$DURATION]))"
    period: "current_calendar_month"
